// Detections for ShieldBreak
// T1562.001 - Impair Defenses: Disable or Modify Tools (Abusing EDR capabilities/remediation engine)
// T1548 - Abuse Elevation Control Mechanism (Exploiting Object Symlinks / Junctions)

// Detection 1 - Detects non-Defender processes loading MpClient.dll
DeviceImageLoadEvents
| where ActionType == "ImageLoaded"
| where FileName == "MpClient.dll"
| where not(
    InitiatingProcessFolderPath startswith @"C:\Program Files\Windows Defender\" or
    InitiatingProcessFolderPath startswith @"C:\ProgramData\Microsoft\Windows Defender\" or
    InitiatingProcessFolderPath startswith @"C:\Windows\System32\" or
    InitiatingProcessFileName =~ "taniumclient.exe" or
    InitiatingProcessParentFileName =~ "taniumclient.exe"
)
| summarize FirstSeen = min(Timestamp), LastSeen = max(Timestamp) by DeviceName, InitiatingProcessFileName, InitiatingProcessFolderPath, InitiatingProcessCommandLine, FolderPath, FileName
| extend HostCustomEntity = DeviceName, ProcessCustomEntity = InitiatingProcessFileName

// Detection 2 - Detects unvetted processes loading the Windows Cloud Filter API
DeviceImageLoadEvents
| where ActionType == "ImageLoaded"
| where FileName == "cldapi.dll"
| where not(
    InitiatingProcessFolderPath startswith @"C:\Windows\System32\" or
    InitiatingProcessFolderPath startswith @"C:\Program Files\" or
    InitiatingProcessFolderPath startswith @"C:\Program Files (x86)\"
)
| project Timestamp, DeviceName, InitiatingProcessFileName, InitiatingProcessFolderPath, InitiatingProcessCommandLine, FileName

// Detection 3 - Detects processes loading both MpClient and Cloud API within 5 minutes, shouldn't happen
let mp_loads = DeviceImageLoadEvents
| where FileName == "MpClient.dll"
| project MpTime = Timestamp, DeviceName, InitiatingProcessFileName, InitiatingProcessFolderPath, InitiatingProcessId;

let cld_loads = DeviceImageLoadEvents
| where FileName == "cldapi.dll"
| project CldTime = Timestamp, DeviceName, InitiatingProcessFileName, InitiatingProcessFolderPath, InitiatingProcessId;

mp_loads
| join kind=inner cld_loads on DeviceName, InitiatingProcessId
| where abs(datetime_diff('minute', MpTime, CldTime)) < 5
| project DeviceName, InitiatingProcessFileName, InitiatingProcessFolderPath, MpTime, CldTime, InitiatingProcessId
